from app.database.models.bosses import Boss

bosses = [
    Boss(name="The Arm", desc="Decrease level of played poker hand"),
    Boss(name="The Club", desc="All Club cards are debuffed"),
    Boss(name="The Eye", desc="No repeat hand types this round"),
    Boss(name="Amber Acorn", desc="Flips and shuffles all Joker cards"),
    Boss(name="Cerulean Bell", desc="Forces 1 card to always be selected"),
    Boss(name="Crimson Heart", desc="One random Joker disabled every hand"),
    Boss(name="Verdant Leaf", desc="All cards debuffed until 1 Joker sold"),
    Boss(name="Violet Vessel", desc="Very large blind"),
    Boss(name="The Fish", desc="Cards drawn face down after each hand played"),
    Boss(name="The Flint", desc="Base Chips and Mult are halved"),
    Boss(name="The Goad", desc="All Spade cards are debuffed"),
    Boss(name="The Head", desc="All Heart cards are debuffed"),
    Boss(name="The Hook", desc="Discards 2 random cards per hand played"),
    Boss(name="The House", desc="First hand is drawn face down"),
    Boss(name="The Manacle", desc="-1 Hand Size"),
    Boss(name="The Mark", desc="All face cards are drawn face down"),
    Boss(name="The Mouth", desc="Play only 1 hand type this round"),
    Boss(name="The Needle", desc="Play only 1 hand"),
    Boss(name="The Ox", desc="Playing a [most-played hand] sets money to $0"),
    Boss(name="The Pillar", desc="Cards played previously this Ante are debuffed"),
    Boss(name="The Plant", desc="All face cards are debuffed"),
    Boss(name="The Psychic", desc="Must play 5 cards"),
    Boss(name="The Serpent", desc="After Play or Discard, always draw 3 cards"),
    Boss(name="The Tooth", desc="Lose $1 per card played"),
    Boss(name="The Wall", desc="Extra large blind"),
    Boss(name="The Water", desc="Start with 0 discards"),
    Boss(name="The Wheel", desc=" in 7 cards get drawn face down"),
    Boss(name="The Window", desc="All Diamond cards are debuffed"),
]
